src/Entity/Ensembles.php
<?php

namespace App\Entity;

use App\Repository\EnsemblesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity(repositoryClass=EnsemblesRepository::class)
 * @Vich\Uploadable
 */
class Ensembles
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

     /**
     * @Vich\UploadableField(mapping="ensembles", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime")
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * @ORM\ManyToMany(targetEntity=Produits::class, inversedBy="ensembles" ,cascade={"persist"}, orphanRemoval=true)
     */
    private $produits;

    /**
     * @ORM\ManyToOne(targetEntity=Budget::class, inversedBy="ensembles")
     * @ORM\JoinColumn(nullable=false)
     * 
     */
    private $Budget;

    /**
     * @ORM\ManyToMany(targetEntity=Saisons::class, inversedBy="ensembles")
     */
    private $Saisons;

    /**
     * @ORM\ManyToMany(targetEntity=Styles::class, inversedBy="ensembles")
     */
    private $Styles;

    /**
     * @ORM\ManyToOne(targetEntity=Genre::class, inversedBy="ensembles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Genre;

    /**
     * @ORM\Column(type="float")
     */
    private $Prix;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $promotion;

    public function __construct()
    {
        $this->produits = new ArrayCollection();
        $this->Saisons = new ArrayCollection();
        $this->Styles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @return Collection|Produits[]
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produits $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits[] = $produit;
            $produit->addEnsemble($this);
        }

        return $this;
    }

    public function removeProduit(Produits $produit): self
    {
        if ($this->produits->removeElement($produit)) {
            $produit->removeEnsemble($this);
        }

        return $this;
    }

    public function getBudget(): ?Budget
    {
        return $this->Budget;
    }

    public function setBudget(?Budget $Budget): self
    {
        $this->Budget = $Budget;

        return $this;
    }

    /**
     * @return Collection|Saisons[]
     */
    public function getSaisons(): Collection
    {
        return $this->Saisons;
    }

    public function addSaison(Saisons $saison): self
    {
        if (!$this->Saisons->contains($saison)) {
            $this->Saisons[] = $saison;
        }

        return $this;
    }

    public function removeSaison(Saisons $saison): self
    {
        $this->Saisons->removeElement($saison);

        return $this;
    }

    /**
     * @return Collection|Styles[]
     */
    public function getStyles(): Collection
    {
        return $this->Styles;
    }

    public function addStyle(Styles $style): self
    {
        if (!$this->Styles->contains($style)) {
            $this->Styles[] = $style;
        }

        return $this;
    }

    public function removeStyle(Styles $style): self
    {
        $this->Styles->removeElement($style);

        return $this;
    }

    public function getGenre(): ?Genre
    {
        return $this->Genre;
    }

    public function setGenre(?Genre $Genre): self
    {
        $this->Genre = $Genre;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->Prix;
    }

    public function getStringPrix(): ?string
    {
        return $this->Prix."€";
    }

    public function setPrix(float $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getPromotion(): ?int
    {
        return $this->promotion;
    }

    public function getStringPromotion(): ?string
    {
        return $this->promotion."%";
    }

    public function getPrixPromotion(): ?float
    {
        return $this->Prix-($this->Prix*($this->promotion/100));
    }

    public function getStringPrixPromotion(): ?String
    {
        return $this->getPrixPromotion()."€";
    }

    public function setPromotion(?int $promotion): self
    {
        $this->promotion = $promotion;

        return $this;
    }
}

templates/default/index.html.twig
{% extends 'indexbase.html.twig' %}

{% block title %}{{ title }}{% endblock %}


{% block articles%}
<div id="articles" class="container grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4  justify-items-center">
    {% for ensemble in ensembles %}
    <!-- component -->
    <div>
      <div class="max-w-xs  bg-white shadow-lg rounded-lg overflow-hidden my-10">
          <div class="px-4 py-2 flex justify-center">
            <h1 class="text-gray-900 font-bold text-sm uppercase">#{{ensemble.styles[0].Nom}}</h1>
          </div>
          <img src="{{ vich_uploader_asset(ensemble,'imageFile')|imagine_filter('ensembles')}}" alt="NIKE AIR">
          <div class="flex items-center justify-between px-4 py-2 bg-cyan">
            <div class="flex justify-center ">
            {% if ensemble.promotion %}
              <span class="text-gray-500 text-xl mx-2 mt-2"><del>{{ensemble.StringPrix}}</del></span>
              <span class="text-black  text-xl mx-2 mt-2">{{ensemble.StringPrixPromotion}}</span>
              <span class="text-xl px-1 text-red-600 m-2">{{ensemble.StringPromotion}}</span>
            {% else %}
              <span class="text-black  text-xl m-2 mt-2">{{ensemble.StringPrix}}</span>
            {% endif %}
            </div>
            <button class="px-4 py-1 bg-black text-sm text-white font-semibold  rounded-full"><a href="{{path(route,{id : ensemble.Id})}}"> En savoir plus</a></button>
          </div>
      </div>
    </div>
    {% endfor %}
    
  </div>
{% endblock %}

templates/default/styleDetails.html.twig
{% extends 'styleDetailsbase.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block products%}
{% for produit in produits %}
  <div class="grid mx-4 my-4  w-10/12" >
    <div class="flex ">
      <div class="p-2 w-11/12 lg:w-8/12 rounded-md shadow-md overflow-hidden">
        <div class="flex justify-center h-3/4 ">
        <img  src="{{ vich_uploader_asset(produit,'imageFile')|imagine_filter('produits')}}" alt="NIKE AIR">
        </div>
        <div class="grid px-5 py-2 justify-items-center h-1/4">
          <h3 class="text-gray-700 uppercase">{{produit.marque}}</h3>
          <div class="flex justify-center ">
          {% if produit.promotion %}
            <span class="text-gray-500 mx-2 mt-2"><del>{{produit.StringPrix}}</del></span>
            <span class="text-gray-700 mx-2 mt-2">{{produit.StringPrixPromotion}}</span>
            <span class="bg-red-500 p-1 mx-2 text-black text-xs mt-2">{{produit.StringPromotion}}</span>
          {% else %}
            <span class="text-gray-700 mx-2 mt-2">{{produit.StringPrix}}</span>
          {% endif %}
          
          </div>
        </div>
      </div>
    
      <div class="flex flex-col">
      <button class="p-2 rounded-full my-5 bg-cyan mx-2 focus:outline-none">
        <svg class="h-5 w-5" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	        viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">
		      <path d="M406,332c-29.636,0-55.969,14.402-72.378,36.571l-141.27-72.195C194.722,288.324,196,279.809,196,271
			    c0-11.931-2.339-23.324-6.574-33.753l148.06-88.958C354.006,167.679,378.59,180,406,180c49.626,0,90-40.374,90-90
			    c0-49.626-40.374-90-90-90c-49.626,0-90,40.374-90,90c0,11.47,2.161,22.443,6.09,32.54l-148.43,89.18
			    C157.152,192.902,132.941,181,106,181c-49.626,0-90,40.374-90,90c0,49.626,40.374,90,90,90c30.122,0,56.832-14.876,73.177-37.666
			    l140.86,71.985C317.414,403.753,316,412.714,316,422c0,49.626,40.374,90,90,90c49.626,0,90-40.374,90-90
			    C496,372.374,455.626,332,406,332z M406,30c33.084,0,60,26.916,60,60s-26.916,60-60,60s-60-26.916-60-60S372.916,30,406,30z
			     M106,331c-33.084,0-60-26.916-60-60s26.916-60,60-60s60,26.916,60,60S139.084,331,106,331z M406,482c-33.084,0-60-26.916-60-60
          s26.916-60,60-60s60,26.916,60,60S439.084,482,406,482z"/>
        </svg>
      </button>

      <button class="p-2 rounded-full bg-cyan mx-2 focus:outline-none">
        <a href="{{ path('favoris' , {id : produit.Id ,  returnId :  ensembleId, type : 'E' }) }}">
          <svg class="h-5 w-5" viewBox="0 0 74 74" width="512" height="512"><path d="M60,72a1,1,0,0,1-.571-.179L37,56.218l-22.429,15.6A1,1,0,0,1,13,71V7a5.006,5.006,0,0,1,5-5H56a5.006,5.006,0,0,1,5,5V71a1,1,0,0,1-1,1ZM37,54a1,1,0,0,1,.571.179L59,69.086V7a3,3,0,0,0-3-3H18a3,3,0,0,0-3,3V69.086L36.429,54.179A1,1,0,0,1,37,54Z"/><path d="M46.2,41.67a1,1,0,0,1-.588-.191L37,35.216l-8.612,6.262a1,1,0,0,1-1.539-1.117l3.287-10.129-8.613-6.263a1,1,0,0,1,.588-1.809H32.754l3.295-10.129a1,1,0,0,1,1.9,0L41.246,22.16H51.89a1,1,0,0,1,.588,1.809l-8.613,6.263,3.287,10.129A1,1,0,0,1,46.2,41.67ZM37,32.98a1,1,0,0,1,.588.191l6.711,4.88-2.561-7.893a1,1,0,0,1,.363-1.117l6.713-4.881H40.52a1,1,0,0,1-.951-.691L37,15.573l-2.568,7.9a1,1,0,0,1-.951.691H25.186L31.9,29.042a1,1,0,0,1,.363,1.117L29.7,38.051l6.711-4.88A1,1,0,0,1,37,32.98Z"/></svg>
        <a>
      </button>

      <button class="p-2 rounded-full my-5 bg-cyan mx-2 focus:outline-none">
        <a href="{{ path('ajouterPanier' , {id : produit.Id}) }}">
          <svg class="h-5 w-5" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="1" viewBox="0 0 24 24" stroke="currentColor"><path d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"></path></svg>
        </a>
      </button>

      </div>
    
    </div>
    <a href="{{path(route,{id : produit.Id})}}"><button class="w-11/12 lg:w-8/12 my-4 px-4 py-1 bg-cyan text-sm text-black font-semibold focus:outline-none rounded-full">En savoir plus</button></a>
  </div>
{% endfor %}

{% endblock %}

{% block articles%}
{% for ensemble in ensembles %}
    <!-- component -->
    <div>
      <div class="max-w-xs  bg-white shadow-lg rounded-lg overflow-hidden my-10">
          <div class="px-4 py-2 flex justify-center">
            <h1 class="text-gray-900 font-bold text-sm uppercase">#{{ensemble.styles[0].Nom}}</h1>
          </div>
          <p>
          <img class=" w-96 h-80"src="{{ vich_uploader_asset(ensemble,'imageFile')|imagine_filter('ensembles')}}" alt="NIKE AIR">
          </p>
          <div class="flex items-center justify-between px-4 py-2 bg-cyan">
            <div class="flex justify-center ">
            {% if ensemble.promotion %}
              <span class="text-gray-500 text-xl mx-2 mt-2"><del>{{ensemble.StringPrix}}</del></span>
              <span class="text-black  text-xl mx-2 mt-2">{{ensemble.StringPrixPromotion}}</span>
              <span class="text-xl px-1 text-red-600 m-2">{{ensemble.StringPromotion}}</span>
            {% else %}
              <span class="text-black  text-xl m-2 mt-2">{{ensemble.StringPrix}}</span>
            {% endif %}
            </div>
            <button class="px-4 py-1 bg-black text-sm text-white font-semibold  rounded-full"><a href="{{path('styleDetails',{id : ensemble.Id})}}"> En savoir plus</a></button>
          </div>
      </div>
    </div>
    {% endfor %}

    <!-- component -->
    <div>
      <div class="max-w-xs bg-white shadow-lg rounded-lg overflow-hidden my-10">
          <div class="px-4 py-2 flex justify-center">
            <h1 class="text-gray-900 font-bold text-sm uppercase">#Tendance</h1>
          </div>
          <img class="h-full w-full object-cover mt-2" src="{{ asset('build/img/exemple.PNG') }}" alt="NIKE AIR">
          <div class="flex items-center justify-between px-4 py-2 bg-cyan">
            <h1 class="text-black font-bold text-xl">$129</h1>
            <button class="px-4 py-1 bg-black text-sm text-white font-semibold  rounded-full"><a href="#"> En savoir plus</a></button>
          </div>
      </div>
    </div>

    <!-- component -->
    <div>
      <div class="max-w-xs bg-white shadow-lg rounded-lg overflow-hidden my-10">
          <div class="px-4 py-2 flex justify-center">
            <h1 class="text-gray-900 font-bold text-sm uppercase">#Tendance</h1>
          </div>
          <img class="h-full w-full object-cover mt-2" src="{{ asset('build/img/exemple.PNG') }}" alt="NIKE AIR">
          <div class="flex items-center justify-between px-4 py-2 bg-cyan">
            <h1 class="text-black font-bold text-xl">$129</h1>
            <button class="px-4 py-1 bg-black text-sm text-white font-semibold  rounded-full"><a href="#"> En savoir plus</a></button>
          </div>
      </div>
    </div>

    <!-- component -->
    <div>
      <div class="max-w-xs bg-white shadow-lg rounded-lg overflow-hidden my-10">
          <div class="px-4 py-2 flex justify-center">
            <h1 class="text-gray-900 font-bold text-sm uppercase">#Tendance</h1>
          </div>
          <img class="h-full w-full object-cover mt-2" src="{{ asset('build/img/exemple.PNG') }}" alt="NIKE AIR">
          <div class="flex items-center justify-between px-4 py-2 bg-cyan">
            <h1 class="text-black font-bold text-xl">$129</h1>
            <button class="px-4 py-1 bg-black text-sm text-white font-semibold  rounded-full"><a href="#"> En savoir plus</a></button>
          </div>
      </div>
    </div>



{% endblock %}